name: KRX data crawller


on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

  schedule:
    # 한국시간 기준 매일 오전 1시에 실행
    # 10으로 설정하니 오후 6시에 돌아감
    - cron: '0 18 * * *'
     

jobs:
  
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 requests pandas google google-cloud-storage oracledb sqlalchemy 
        python -m pip install finance-datareader plotly
        python -m pip install bs4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run crawlling
      env:
        STORAGE_NAME: ${{ secrets.STORAGE_NAME }}
        WALLET_FILE: ${{ secrets.WALLET_FILE }}
        
        GCP_TYPE: ${{ secrets.GCP_TYPE }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_PRIVATE_KEY_ID: ${{ secrets.GCP_PRIVATE_KEY_ID }}
        GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
        GCP_CLIENT_EMAIL: ${{ secrets.GCP_CLIENT_EMAIL }}
        GCP_CLIENT_ID: ${{ secrets.GCP_CLIENT_ID }}
        GCP_AUTH_URI: ${{ secrets.GCP_AUTH_URI }}
        GCP_TOKEN_URI: ${{ secrets.GCP_TOKEN_URI }}
        GCP_PROVIDER_URL: ${{ secrets.GCP_PROVIDER_URL }}
        GCP_CLIENT_URL: ${{ secrets.GCP_CLIENT_URL }}
        GCP_UNIV_DOMAIN: ${{ secrets.GCP_UNIV_DOMAIN }}

        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_DSN: ${{ secrets.DB_DSN }}
        DB_WALLET_PASSWORD: ${{ secrets.DB_WALLET_PASSWORD }}

      run: |
        python "crawller.py"
    - name: commit
      run: |
        git config --local user.email "tmdduq9008@gmail.com"
        git config --local user.name "SEUNGTO"
        git add new_data.json old_data.json code_list.json research.json ewm_data.json etf_target_price.json nid_list.json
        git commit -m "update data"

    - name: push
      uses : ad-m/github-push-action@master
      with :
         branch : ${{ github.ref }}
         github_token : ${{ secrets.TOKEN }}
